apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xasuewgqd-go-gitops
  description: This is GitOps manifest for xasuewgqd-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xasuewgqd-go
    backstage.io/kubernetes-id: xasuewgqd-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xasuewgqd-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xasuewgqd-go
